# Use OpenJDK 21 runtime as the base image
FROM openjdk:21-jdk-alpine

# Set the working directory
WORKDIR /FNPBLOG

# Copy the built JAR file into the container
COPY target/fnpblog-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
