version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Adii@9389
      MYSQL_DATABASE: fnpblog
      MYSQL_USER: root
      MYSQL_PASSWORD: Adii@9389
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Adii@9389
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: angular_app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: